Sonar fixes
brsbalazs/iet-lab pull request #3
Opened 2021-04-24 17:43 UTC by brsbalazs

2021-04-25 15:57 UTC, 1m0d approved these changes

2021-04-25 15:58 UTC, 1m0d commented
great job!

2021-04-30 10:27 UTC, 1m0d requested changes
rookie mistakes, I was expecting more from you :(

2021-04-30 10:27 UTC, 1m0d commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
> +  Random generator = new Random();
use SecureRandom instead
SecureRandom generator = new SecureRandom();

2021-04-30 10:27 UTC, 1m0d commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
>      double r = generator.nextDouble();
use var instead of double

2021-05-01 10:26 UTC, brsbalazs commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
> +  Random generator = new Random();
Has been fixed in  https://github.com/brsbalazs/iet-lab/pull/3/commits/74699656ab1c0bf17d2a9376e2722d1dda1b8e7c

2021-05-01 10:27 UTC, brsbalazs commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
>      double r = generator.nextDouble();
Find the fiexes in https://github.com/brsbalazs/iet-lab/pull/3/commits/74699656ab1c0bf17d2a9376e2722d1dda1b8e7c

2021-05-01 10:33 UTC, 1m0d commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
>  import java.util.Random;
useless import

2021-05-01 10:42 UTC, brsbalazs commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
>  import java.util.Random;
removed https://github.com/brsbalazs/iet-lab/pull/3/commits/da6a3332285cb5f7e6d79cda3ae19aff5fdaed1f

2021-05-01 10:44 UTC, 1m0d approved these changes

2021-05-01 10:45 UTC, merged